In [1]:
#The elements in the example arrays above can be accessed by indexing like lists in Python such that:

In [4]:
import numpy as np

In [6]:
a[0] = 6,  a[3] = 9, b[0, 0] = 1 , b[1, 2] = 6 c[0, 1] = 8

SyntaxError: invalid syntax (<ipython-input-6-b4339fa11b5d>, line 1)

In [7]:
d[1,  0:2]

NameError: name 'd' is not defined

In [8]:
e = np.array([[10, 11, 12],[13, 14, 15], 
              [16, 17, 18],[19, 20, 21]])

In [9]:
e[:3, :2]

array([[10, 11],
       [13, 14],
       [16, 17]])

In [10]:
e[:4,:2]

array([[10, 11],
       [13, 14],
       [16, 17],
       [19, 20]])

In [11]:
e[:4, :1]

array([[10],
       [13],
       [16],
       [19]])

In [12]:
e[[2, 0, 3, 1],[2, 1, 0, 2]]

array([18, 11, 19, 15])

In [13]:
e[e>15]

array([16, 17, 18, 19, 20, 21])

In [14]:
e[e<=15]

array([10, 11, 12, 13, 14, 15])

In [15]:

c = np.array([[9.0, 8.0, 7.0], [1.0, 2.0, 3.0]])
d = np.array([[4.0, 5.0, 6.0], [9.0, 8.0, 7.0]])

In [16]:
c + d

array([[13., 13., 13.],
       [10., 10., 10.]])

In [17]:
c - d

array([[ 5.,  3.,  1.],
       [-8., -6., -4.]])

In [18]:
5 / d

array([[1.25      , 1.        , 0.83333333],
       [0.55555556, 0.625     , 0.71428571]])

In [19]:
c **2

array([[81., 64., 49.],
       [ 1.,  4.,  9.]])